ProyectoEgc/decide-single-picasso

decide/booth/static/booth/style.css
decide/booth/templates/booth/booth.html
decide/visualizer/templates/visualizer/visualizer.html

Booth and Visualizer UI changed

refactor(initial): Study usability and define a new usable interface

---

decide/authentication/templates/signup.html
decide/authentication/views.py
decide/decide/urls.py

First version of the user register. Added the form and functionality to register users (without CSS)

add(initial): User register

---

requirements.txt

Added django-import-export dependency to the requirements file

fix(inital): Requirements fixed

---

decide/authentication/templates/authentication/decide.html
decide/authentication/templates/authentication/login.html
decide/authentication/templates/signup.html
decide/authentication/views.py

add(update):UI

---

.github/workflows/django.yml

refactor(init)Update django.yml

---

.github/workflows/django.yml

Changed an error in migrations

refactor(update):Fixed error

---

.github/workflows/django.yml

refactor(fix):Fixed django.yml

---

.github/workflows/django.yml

refactor(update):Fixed

---

.github/ISSUE_TEMPLATE/bug_report.md

Implemented bug template for issues

Docs(init): Done bug template

---

decide/authentication/templates/authentication/decide.html

Solved closed votes that did not appear Close #48

bug(initial): Closed Votings bug

---

decide/authentication/templates/signup.html
decide/authentication/views.py

Added CSS styles to the registration form, fixed redirection, and corrected error handling.

refactor(initial): User register

---

requirements.txt

Added Pillow dependecy on requirements.txt

fix(initial): Fix requirements.txt

---

decide/authentication/tests_selenium.py
decide/voting/tests.py
decide/voting/views.py

fix(update): Test failing in develop branch

---

decide/authentication/test_selenium_create_user.py
decide/authentication/test_selenium_negative_create_user.py

added positive and negative test cases for admin

test(initial): Authentication test

---

decide/voting/test_selenium_create_yes_no_question.py
decide/voting/tests.py

add(update): Yes No Tests

---

decide/postproc/tests.py
decide/voting/tests.py

add(end): Score voting tests

---

decide/census/test_selenium_export.py
decide/census/test_selenium_import.py
decide/voting/test_selenium_negative_create_multiple_voting.py

Tests updated excepting test_selenium from voting

fix(update): Tests failling in develop branch

---

.github/workflows/django.yml

fix(update): Fix actions

---

.github/workflows/django.yml
decide/authentication/test_selenium_create_user.py
decide/census/test_selenium_export.py
decide/census/test_selenium_import.py
decide/voting/test_selenium.py
decide/voting/test_selenium_create_score_question.py
decide/voting/test_selenium_create_score_question_negative.py
decide/voting/test_selenium_create_yes_no_question.py
decide/voting/test_selenium_positive_create_multiple_voting.py
requirements.txt

fix(update): Failing tests in develop branch

---

decide/voting/test_selenium.py
decide/voting/tests.py

Deleted selenium test and added new test

test(update): Image Voting

---

decide/authentication/test_selenium_create_user.py
decide/authentication/test_selenium_negative_create_user.py
decide/authentication/tests_selenium.py
decide/census/test_selenium_export.py
decide/census/test_selenium_import.py
decide/voting/test_selenium.py
decide/voting/test_selenium_create_score_question.py
decide/voting/test_selenium_create_score_question_negative.py
decide/voting/test_selenium_create_yes_no_question.py
decide/voting/test_selenium_negative_create_multiple_voting.py
decide/voting/test_selenium_negative_create_question.py
decide/voting/test_selenium_positive_create_multiple_voting.py

Implemented annotations for test bugs in actions

add(initial): Tests CI bug
